# Generated by Django 3.0.1 on 2020-08-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200825_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketproduct',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
